import type {Pool,PoolClient} from "pg";

export const UNIT_TYPES={
 pirate_infantry:{category:"infantry",health:100,attack:14,defense:12,range:1,speed:3,abilityIds:["shield_wall"],wood:20,steel:5,food:10},
 swordsman:{category:"infantry",health:110,attack:18,defense:14,range:1,speed:3,abilityIds:["heavy_strike"],wood:15,steel:12,food:10},
 spearman:{category:"infantry",health:105,attack:16,defense:18,range:2,speed:3,abilityIds:["brace"],wood:15,steel:10,food:10},
 musketeer:{category:"infantry",health:80,attack:24,defense:8,range:6,speed:2,abilityIds:["volley"],wood:10,steel:18,food:10},
 archer:{category:"infantry",health:75,attack:20,defense:7,range:7,speed:3,abilityIds:["volley"],wood:18,steel:4,food:8},
 mermaid_mage:{category:"magic",health:85,attack:26,defense:8,range:6,speed:3,abilityIds:["tidal_wave"],wood:5,steel:5,food:15},
 elemental_warrior:{category:"magic",health:125,attack:28,defense:16,range:2,speed:3,abilityIds:["elemental_burst"],wood:5,steel:20,food:15},
 water_spirit:{category:"magic",health:95,attack:22,defense:10,range:5,speed:4,abilityIds:["healing_tide"],wood:5,steel:5,food:18},
 fire_spirit:{category:"magic",health:90,attack:30,defense:8,range:5,speed:4,abilityIds:["burning_wave"],wood:5,steel:5,food:18},
 dragon:{category:"creature",health:260,attack:48,defense:28,range:5,speed:5,abilityIds:["dragon_breath"],wood:20,steel:40,food:30},
 giant:{category:"creature",health:300,attack:42,defense:35,range:1,speed:2,abilityIds:["crushing_blow"],wood:20,steel:35,food:30},
 behemoth:{category:"creature",health:420,attack:55,defense:40,range:2,speed:2,abilityIds:["siege_roar"],wood:30,steel:50,food:40},
 cannon:{category:"siege",health:150,attack:60,defense:12,range:10,speed:1,abilityIds:["cannon_shot"],wood:30,steel:50,food:5},
 mortar:{category:"siege",health:120,attack:70,defense:10,range:12,speed:1,abilityIds:["indirect_fire"],wood:35,steel:60,food:5},
 ballista:{category:"siege",health:130,attack:65,defense:14,range:11,speed:1,abilityIds:["piercing_bolt"],wood:40,steel:55,food:5},
 magic_artillery:{category:"siege",health:140,attack:80,defense:16,range:13,speed:1,abilityIds:["arcane_barrage"],wood:20,steel:70,food:10},
} as const;
export type UnitType=keyof typeof UNIT_TYPES;
export const ASSIGNMENTS=["garrison","patrol","expedition","resource_protection","guild_mission","realm_warfare","invasion","convoy","naval"] as const;
export type ArmyAssignment=typeof ASSIGNMENTS[number];
export const FORMATIONS=["line","wedge","column","box","ranged","siege","custom"] as const;
export const ORDERS=["move","attack","defend","retreat","rally","reinforce","hold","focus_fire"] as const;
export const DEFENSE_TYPES=["archer_tower","musket_tower","cannon_tower","magic_tower","mermaid_tower","dragon_tower","wall","gate","spike_trap","fire_trap","water_trap","net_trap","explosive_barrel","magic_trap"] as const;
export type FormationType=typeof FORMATIONS[number]; export type CommanderOrder=typeof ORDERS[number]; export type DefenseType=typeof DEFENSE_TYPES[number];

export interface ArmyUnit{id:string;unitType:UnitType;category:string;quantity:number;health:number;maxHealth:number;attack:number;defense:number;range:number;speed:number;abilityIds:string[];sourceCreatureId:string|null}
export interface ArmyState{id:string;ownerUserId:string;name:string;assignment:ArmyAssignment;commanderUserId:string|null;status:string;units:ArmyUnit[];garrisonBaseIds:string[];activeFormation:{id:string;name:string;formationType:FormationType;layout:Record<string,unknown>}|null}
export interface BattleState{id:string;attackerArmyId:string;defenderArmyId:string|null;status:string;turn:number;units:Array<{armyUnitId:string;side:"attacker"|"defender";deployed:boolean;formationSlot:number|null;currentHealth:number;retreating:boolean}>}

function validUnit(v:string):UnitType{if(Object.hasOwn(UNIT_TYPES,v))return v as UnitType;throw new Error("INVALID_ARMY_UNIT_TYPE")}
function validAssignment(v:string):ArmyAssignment{if((ASSIGNMENTS as readonly string[]).includes(v))return v as ArmyAssignment;throw new Error("INVALID_ARMY_ASSIGNMENT")}
function validFormation(v:string):FormationType{if((FORMATIONS as readonly string[]).includes(v))return v as FormationType;throw new Error("INVALID_ARMY_FORMATION")}
function validOrder(v:string):CommanderOrder{if((ORDERS as readonly string[]).includes(v))return v as CommanderOrder;throw new Error("INVALID_COMMANDER_ORDER")}
function validDefense(v:string):DefenseType{if((DEFENSE_TYPES as readonly string[]).includes(v))return v as DefenseType;throw new Error("INVALID_DEFENSIVE_STRUCTURE")}
function unitRow(r:{id:string;unit_type:UnitType;category:string;quantity:number;health:number;max_health:number;attack:number;defense:number;range:number;speed:number;ability_ids:string[];source_creature_id:string|null}):ArmyUnit{return {id:r.id,unitType:r.unit_type,category:r.category,quantity:r.quantity,health:r.health,maxHealth:r.max_health,attack:r.attack,defense:r.defense,range:r.range,speed:r.speed,abilityIds:r.ability_ids??[],sourceCreatureId:r.source_creature_id}}
async function base(c:PoolClient,userId:string){const r=await c.query<{id:string}>("SELECT id FROM player_bases WHERE owner_user_id=$1 FOR UPDATE",[userId]);if(!r.rows[0])throw new Error("BASE_NOT_FOUND");return r.rows[0].id}
async function barracks(c:PoolClient,baseId:string){const r=await c.query("SELECT id FROM base_buildings WHERE base_id=$1 AND type='barracks' AND active=true LIMIT 1",[baseId]);if(!r.rows[0])throw new Error("BARRACKS_REQUIRED")}
async function resources(c:PoolClient,baseId:string,cost:Record<string,number>){for(const [k,v] of Object.entries(cost)){const r=await c.query<{quantity:string}>("SELECT quantity FROM base_storage WHERE base_id=$1 AND resource_key=$2 FOR UPDATE",[baseId,k]);if(Number(r.rows[0]?.quantity??0)<v)throw new Error("INSUFFICIENT_BASE_RESOURCES");await c.query("UPDATE base_storage SET quantity=quantity-$3,updated_at=CURRENT_TIMESTAMP WHERE base_id=$1 AND resource_key=$2",[baseId,k,v])}}
async function commander(c:PoolClient,userId:string,armyId:string,battleId:string|null){const a=await c.query<{owner_user_id:string;commander_user_id:string|null}>("SELECT owner_user_id,commander_user_id FROM armies WHERE id=$1 FOR UPDATE",[armyId]);if(!a.rows[0])throw new Error("ARMY_NOT_FOUND");if(a.rows[0].owner_user_id===userId||a.rows[0].commander_user_id===userId)return;const g=await c.query<{guild_id:string}>("SELECT guild_id FROM guild_members WHERE user_id=$1 AND rank IN ('master','officer') LIMIT 1",[userId]);if(!g.rows[0])throw new Error("COMMANDER_PERMISSION_DENIED");const n=await c.query("SELECT 1 FROM army_commander_nominations WHERE guild_id=$1 AND user_id=$2",[g.rows[0].guild_id,userId]);if(!n.rows[0])throw new Error("COMMANDER_PERMISSION_DENIED");if(battleId){const b=await c.query<{owner_user_id:string}>("SELECT owner_user_id FROM army_battles WHERE id=$1",[battleId]);if(b.rows[0]?.owner_user_id!==userId)throw new Error("COMMANDER_PERMISSION_DENIED")}}

export class ArmyStore{
 constructor(private readonly db:Pool){}
 async create(userId:string,name:string){const c=await this.db.connect();try{await c.query("BEGIN");const b=await base(c,userId);await barracks(c,b);const r=await c.query<{id:string}>("INSERT INTO armies(owner_user_id,name) VALUES($1,$2) RETURNING id",[userId,name.trim().slice(0,64)||"First Company"]);await c.query("COMMIT");return this.get(userId,r.rows[0].id)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async train(userId:string,armyId:string,type:string,quantity:number){const t=validUnit(type);if(!Number.isSafeInteger(quantity)||quantity<1||quantity>1000)throw new Error("INVALID_TRAINING_QUANTITY");const s=UNIT_TYPES[t],c=await this.db.connect();try{await c.query("BEGIN");const b=await base(c,userId);await barracks(c,b);if(!(await c.query("SELECT id FROM armies WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[armyId,userId])).rows[0])throw new Error("ARMY_NOT_FOUND");await resources(c,b,{wood:s.wood*quantity,steel:s.steel*quantity,food:s.food*quantity});const q=await c.query<{id:string;completes_at:Date}>("INSERT INTO army_training_queue(army_id,unit_type,quantity,completes_at) VALUES($1,$2,$3,CURRENT_TIMESTAMP+($4||' seconds')::interval) RETURNING id,completes_at",[armyId,t,quantity,Math.max(5,Math.ceil(quantity/10)*5)]);await c.query("UPDATE armies SET status='training',updated_at=CURRENT_TIMESTAMP WHERE id=$1",[armyId]);await c.query("COMMIT");return {queueId:q.rows[0].id,completesAt:q.rows[0].completes_at.toISOString()}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 private async complete(c:PoolClient,armyId:string){const q=await c.query<{id:string;unit_type:UnitType;quantity:number}>("SELECT id,unit_type,quantity FROM army_training_queue WHERE army_id=$1 AND status='training' AND completes_at<=CURRENT_TIMESTAMP FOR UPDATE",[armyId]);for(const x of q.rows){const s=UNIT_TYPES[x.unit_type],e=await c.query<{id:string;quantity:number;max_health:number}>("SELECT id,quantity,max_health FROM army_units WHERE army_id=$1 AND unit_type=$2 AND source_creature_id IS NULL FOR UPDATE",[armyId,x.unit_type]);if(e.rows[0]){const total=e.rows[0].quantity+x.quantity;await c.query("UPDATE army_units SET quantity=$2,health=$3,max_health=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[e.rows[0].id,total,total*s.health,total*s.health])}else await c.query("INSERT INTO army_units(army_id,unit_type,category,quantity,health,max_health,attack,defense,range,speed,ability_ids) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb)",[armyId,x.unit_type,s.category,x.quantity,x.quantity*s.health,x.quantity*s.health,s.attack,s.defense,s.range,s.speed,JSON.stringify(s.abilityIds)]);await c.query("UPDATE army_training_queue SET status='completed' WHERE id=$1",[x.id])}await c.query("UPDATE armies SET status='ready',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND NOT EXISTS(SELECT 1 FROM army_training_queue WHERE army_id=$1 AND status='training')",[armyId])}
 async get(userId:string,armyId:string):Promise<ArmyState>{const c=await this.db.connect();try{await c.query("BEGIN");const a=await c.query<{id:string;owner_user_id:string;name:string;assignment:ArmyAssignment;commander_user_id:string|null;status:string}>("SELECT id,owner_user_id,name,assignment,commander_user_id,status FROM armies WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[armyId,userId]);if(!a.rows[0])throw new Error("ARMY_NOT_FOUND");await this.complete(c,armyId);const u=await c.query<{id:string;unit_type:UnitType;category:string;quantity:number;health:number;max_health:number;attack:number;defense:number;range:number;speed:number;ability_ids:string[];source_creature_id:string|null}>("SELECT id,unit_type,category,quantity,health,max_health,attack,defense,range,speed,ability_ids,source_creature_id FROM army_units WHERE army_id=$1 ORDER BY created_at,id",[armyId]);const g=await c.query<{base_id:string}>("SELECT base_id FROM army_garrisons WHERE army_id=$1",[armyId]);const f=await c.query<{id:string;name:string;formation_type:FormationType;layout:Record<string,unknown>}>("SELECT id,name,formation_type,layout FROM army_formations WHERE army_id=$1 AND is_active=true LIMIT 1",[armyId]);await c.query("COMMIT");return {id:a.rows[0].id,ownerUserId:a.rows[0].owner_user_id,name:a.rows[0].name,assignment:a.rows[0].assignment,commanderUserId:a.rows[0].commander_user_id,status:a.rows[0].status,units:u.rows.map(unitRow),garrisonBaseIds:g.rows.map(x=>x.base_id),activeFormation:f.rows[0]??null}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async list(userId:string){const r=await this.db.query<{id:string}>("SELECT id FROM armies WHERE owner_user_id=$1 ORDER BY created_at,id",[userId]);const out:ArmyState[]=[];for(const x of r.rows)out.push(await this.get(userId,x.id));return out}
 async assignment(userId:string,armyId:string,value:string){validAssignment(value);const c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("UPDATE armies SET assignment=$3,status='deployed',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND owner_user_id=$2 RETURNING id",[armyId,userId])).rows[0])throw new Error("ARMY_NOT_FOUND");await c.query("COMMIT");return this.get(userId,armyId)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async garrison(userId:string,armyId:string,baseId:string){const c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("SELECT id FROM player_bases WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[baseId,userId])).rows[0])throw new Error("BASE_NOT_FOUND");if(!(await c.query("SELECT id FROM armies WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[armyId,userId])).rows[0])throw new Error("ARMY_NOT_FOUND");await c.query("INSERT INTO army_garrisons(base_id,army_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[baseId,armyId]);await c.query("UPDATE armies SET assignment='garrison',status='deployed' WHERE id=$1",[armyId]);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async addCreature(userId:string,armyId:string,creatureId:string){const c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("SELECT id FROM armies WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[armyId,userId])).rows[0])throw new Error("ARMY_NOT_FOUND");const r=await c.query<{id:string;species:string;health:number;max_health:number;attack:number;defense:number;ability_ids:string[];tame_progress:number;party_slot:number|null}>("SELECT id,species,health,max_health,attack,defense,ability_ids,tame_progress,party_slot FROM player_creatures WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[creatureId,userId]);if(!r.rows[0])throw new Error("CREATURE_NOT_FOUND");if(r.rows[0].tame_progress<100)throw new Error("CREATURE_NOT_TAMED");if(r.rows[0].party_slot!==null)throw new Error("CREATURE_IN_PARTY");if((await c.query("SELECT 1 FROM army_units WHERE source_creature_id=$1",[creatureId])).rows[0])throw new Error("CREATURE_ALREADY_GARRISONED");const x=r.rows[0];const u=await c.query<{id:string;unit_type:UnitType;category:string;quantity:number;health:number;max_health:number;attack:number;defense:number;range:number;speed:number;ability_ids:string[];source_creature_id:string|null}>("INSERT INTO army_units(army_id,unit_type,category,quantity,health,max_health,attack,defense,range,speed,ability_ids,source_creature_id) VALUES($1,$2,'creature',1,$3,$4,$5,$6,3,3,$7::jsonb,$8) RETURNING id,unit_type,category,quantity,health,max_health,attack,defense,range,speed,ability_ids,source_creature_id",[armyId,x.species,x.health,x.max_health,x.attack,x.defense,JSON.stringify(x.ability_ids??[]),creatureId]);await c.query("UPDATE player_creatures SET ai_mode='stay',updated_at=CURRENT_TIMESTAMP WHERE id=$1",[creatureId]);await c.query("COMMIT");return unitRow(u.rows[0])}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async formation(userId:string,armyId:string,name:string,type:string,layout:Record<string,unknown>){const f=validFormation(type),c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("SELECT id FROM armies WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[armyId,userId])).rows[0])throw new Error("ARMY_NOT_FOUND");await c.query("UPDATE army_formations SET is_active=false WHERE army_id=$1",[armyId]);await c.query("INSERT INTO army_formations(army_id,name,formation_type,layout,is_active) VALUES($1,$2,$3,$4::jsonb,true)",[armyId,name.trim().slice(0,32)||"Formation",f,JSON.stringify(layout)]);await c.query("COMMIT");return this.get(userId,armyId)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async nominateCommander(userId:string,guildId:string,targetUserId:string){const c=await this.db.connect();try{await c.query("BEGIN");const g=await c.query<{rank:string}>("SELECT rank FROM guild_members WHERE guild_id=$1 AND user_id=$2 FOR UPDATE",[guildId,userId]);if(!g.rows[0]||!["master","officer"].includes(g.rows[0].rank))throw new Error("GUILD_PERMISSION_DENIED");if(!(await c.query("SELECT 1 FROM guild_members WHERE guild_id=$1 AND user_id=$2",[guildId,targetUserId])).rows[0])throw new Error("GUILD_MEMBER_NOT_FOUND");await c.query("INSERT INTO army_commander_nominations(guild_id,user_id,appointed_by) VALUES($1,$2,$3) ON CONFLICT(guild_id,user_id) DO UPDATE SET appointed_by=EXCLUDED.appointed_by",[guildId,targetUserId,userId]);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async commander(userId:string,armyId:string,targetUserId:string){const c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("SELECT owner_user_id FROM armies WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[armyId,userId])).rows[0])throw new Error("ARMY_NOT_FOUND");const g=await c.query<{guild_id:string}>("SELECT guild_id FROM guild_members WHERE user_id=$1 LIMIT 1",[userId]);if(targetUserId!==userId){if(!g.rows[0]||!(await c.query("SELECT 1 FROM army_commander_nominations WHERE guild_id=$1 AND user_id=$2",[g.rows[0].guild_id,targetUserId])).rows[0])throw new Error("COMMANDER_NOT_NOMINATED")}await c.query("UPDATE armies SET commander_user_id=$2 WHERE id=$1",[armyId,targetUserId]);await c.query("COMMIT");return this.get(userId,armyId)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async order(userId:string,armyId:string,battleId:string|null,type:string,targetUnitId:string|null,targetX:number|null,targetY:number|null,payload:Record<string,unknown>){const o=validOrder(type),c=await this.db.connect();try{await c.query("BEGIN");await commander(c,userId,armyId,battleId);if(targetUnitId&&!(await c.query("SELECT 1 FROM army_units WHERE id=$1 AND army_id=$2",[targetUnitId,armyId])).rows[0])throw new Error("ARMY_UNIT_NOT_FOUND");await c.query("INSERT INTO commander_orders(army_id,battle_id,commander_user_id,order_type,target_unit_id,target_x,target_y,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)",[armyId,battleId,userId,o,targetUnitId,targetX,targetY,JSON.stringify(payload)]);if(o==="retreat")await c.query("UPDATE armies SET status='retreating' WHERE id=$1",[armyId]);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async battleCreate(userId:string,attackerArmyId:string,defenderArmyId:string|null,x:number,y:number){const c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("SELECT id FROM armies WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[attackerArmyId,userId])).rows[0])throw new Error("ARMY_NOT_FOUND");if(defenderArmyId){if(!(await c.query("SELECT id FROM armies WHERE id=$1 FOR UPDATE",[defenderArmyId])).rows[0])throw new Error("DEFENDER_ARMY_NOT_FOUND")}const b=await c.query<{id:string}>("INSERT INTO army_battles(attacker_army_id,defender_army_id,owner_user_id,seed,target_x,target_y) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[attackerArmyId,defenderArmyId,userId,BigInt(Date.now()).toString(),x,y]);for(const side of [["attacker",attackerArmyId],["defender",defenderArmyId] as const] as Array<["attacker"|"defender",string|null]>){if(!side[1])continue;const us=await c.query<{id:string;health:number}>("SELECT id,health FROM army_units WHERE army_id=$1",[side[1]]);for(const u of us.rows)await c.query("INSERT INTO battle_units(battle_id,army_unit_id,side,current_health) VALUES($1,$2,$3,$4)",[b.rows[0].id,u.id,side[0],u.health])}await c.query("COMMIT");return this.battle(b.rows[0].id,userId)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async deploy(userId:string,battleId:string,unitId:string,slot:number){if(!Number.isSafeInteger(slot)||slot<0||slot>999)throw new Error("INVALID_FORMATION_SLOT");const c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("SELECT id FROM army_battles WHERE id=$1 AND owner_user_id=$2 AND status='active' FOR UPDATE",[battleId,userId])).rows[0])throw new Error("BATTLE_NOT_FOUND");if(!(await c.query("SELECT 1 FROM battle_units WHERE battle_id=$1 AND army_unit_id=$2",[battleId,unitId])).rows[0])throw new Error("BATTLE_UNIT_NOT_FOUND");await c.query("UPDATE battle_units SET deployed=true,formation_slot=$3 WHERE battle_id=$1 AND army_unit_id=$2",[battleId,unitId,slot]);await c.query("INSERT INTO commander_orders(battle_id,commander_user_id,order_type,target_unit_id,payload) VALUES($1,$2,'move',$3,$4::jsonb)",[battleId,userId,unitId,JSON.stringify({formationSlot:slot})]);await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async turn(userId:string,battleId:string){const c=await this.db.connect();try{await c.query("BEGIN");const b=await c.query<{id:string;turn:number;status:string}>("SELECT id,turn,status FROM army_battles WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[battleId,userId]);if(!b.rows[0])throw new Error("BATTLE_NOT_FOUND");if(b.rows[0].status!=="active")throw new Error("BATTLE_NOT_ACTIVE");const rows=await c.query<{army_unit_id:string;side:"attacker"|"defender";current_health:number}>("SELECT army_unit_id,side,current_health FROM battle_units WHERE battle_id=$1 AND deployed=true AND current_health>0 AND retreating=false ORDER BY side,army_unit_id",[battleId]);const sides={attacker:rows.rows.filter(x=>x.side==="attacker"),defender:rows.rows.filter(x=>x.side==="defender")};if(!sides.attacker.length||!sides.defender.length){const status=sides.attacker.length?"attacker_won":"defender_won";await c.query("UPDATE army_battles SET status=$2 WHERE id=$1",[battleId,status]);await c.query("COMMIT");return this.battle(battleId,userId)}const ids=rows.rows.map(x=>x.army_unit_id),stats=await c.query<{id:string;attack:number;defense:number;quantity:number}>("SELECT id,attack,defense,quantity FROM army_units WHERE id=ANY($1::uuid[]) FOR UPDATE",[ids]),map=new Map(stats.rows.map(x=>[x.id,x]));const damage=new Map<string,number>();for(const u of rows.rows){const enemy=u.side==="attacker"?sides.defender:sides.attacker;const target=enemy[0];const s=map.get(u.army_unit_id),t=map.get(target.army_unit_id);if(s&&t)damage.set(target.army_unit_id,(damage.get(target.army_unit_id)??0)+Math.max(1,Math.floor(s.attack*s.quantity-t.defense*t.quantity/2)))}for(const [id,d] of damage)await c.query("UPDATE battle_units SET current_health=GREATEST(0,current_health-$3) WHERE battle_id=$1 AND army_unit_id=$2",[battleId,id,d]);const alive=await c.query<{side:"attacker"|"defender"}>("SELECT DISTINCT side FROM battle_units WHERE battle_id=$1 AND deployed=true AND current_health>0 AND retreating=false",[battleId]);const status=alive.rows.length<2?(alive.rows[0]?.side==="attacker"?"attacker_won":"defender_won"):"active";await c.query("UPDATE army_battles SET turn=turn+1,status=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[battleId,status]);await c.query("INSERT INTO commander_orders(battle_id,commander_user_id,order_type,payload) VALUES($1,$2,'attack',$3::jsonb)",[battleId,userId,JSON.stringify({turn:b.rows[0].turn+1,serverResolved:true})]);await c.query("COMMIT");return this.battle(battleId,userId)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async battle(battleId:string,userId:string):Promise<BattleState>{const b=await this.db.query<{id:string;attacker_army_id:string;defender_army_id:string|null;status:string;turn:number}>("SELECT id,attacker_army_id,defender_army_id,status,turn FROM army_battles WHERE id=$1 AND owner_user_id=$2",[battleId,userId]);if(!b.rows[0])throw new Error("BATTLE_NOT_FOUND");const u=await this.db.query<{army_unit_id:string;side:"attacker"|"defender";deployed:boolean;formation_slot:number|null;current_health:number;retreating:boolean}>("SELECT army_unit_id,side,deployed,formation_slot,current_health,retreating FROM battle_units WHERE battle_id=$1 ORDER BY side,formation_slot NULLS LAST,army_unit_id",[battleId]);return {id:b.rows[0].id,attackerArmyId:b.rows[0].attacker_army_id,defenderArmyId:b.rows[0].defender_army_id,status:b.rows[0].status,turn:b.rows[0].turn,units:u.rows}}
 async defense(userId:string,baseId:string,type:string,x:number,y:number){const t=validDefense(type);if(!Number.isSafeInteger(x)||!Number.isSafeInteger(y)||Math.abs(x)>128||Math.abs(y)>128)throw new Error("INVALID_DEFENSE_POSITION");const c=await this.db.connect();try{await c.query("BEGIN");if(!(await c.query("SELECT id FROM player_bases WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[baseId,userId])).rows[0])throw new Error("BASE_NOT_FOUND");if((await c.query("SELECT 1 FROM base_buildings WHERE base_id=$1 AND grid_x=$2 AND grid_y=$3 AND active=true UNION ALL SELECT 1 FROM base_defensive_structures WHERE base_id=$1 AND grid_x=$2 AND grid_y=$3 AND active=true LIMIT 1",[baseId,x,y])).rows[0])throw new Error("DEFENSE_POSITION_OCCUPIED");const cost=t.includes("tower")?{wood:100,steel:50}:{wood:50,steel:25};await resources(c,baseId,cost);const hp=t.includes("tower")?500:300,ammo=t==="cannon_tower"?10:0,r=await c.query<{id:string}>("INSERT INTO base_defensive_structures(base_id,structure_type,grid_x,grid_y,health,max_health,ammo) VALUES($1,$2,$3,$4,$5,$5,$6) RETURNING id",[baseId,t,x,y,hp,ammo]);await c.query("COMMIT");return {id:r.rows[0].id,type:t,level:1}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async defenses(userId:string,baseId:string):Promise<Array<{id:string;type:DefenseType;grid_x:number;grid_y:number;level:number;health:number;max_health:number;ammo:number;active:boolean}>>{const r=await this.db.query<{id:string;type:DefenseType;grid_x:number;grid_y:number;level:number;health:number;max_health:number;ammo:number;active:boolean}>("SELECT id,structure_type AS type,grid_x,grid_y,level,health,max_health,ammo,active FROM base_defensive_structures WHERE base_id=$1 AND EXISTS(SELECT 1 FROM player_bases WHERE id=$1 AND owner_user_id=$2) ORDER BY grid_y,grid_x,id",[baseId,userId]);return r.rows}
 async nominateDefenseCommander(userId:string,guildId:string,targetUserId:string){return this.nominateCommander(userId,guildId,targetUserId)}
}