import type {Pool,PoolClient} from "pg";

interface RealmRow{id:string;name:string;faction_type:string;population:string;economy:string;military_strength:string;resources:Record<string,unknown>;ai_state:Record<string,unknown>;capital_x:number;capital_y:number}
interface TerritoryRow{id:string;name:string;min_x:number;max_x:number;min_y:number;max_y:number;realm_owner_id:string|null;guild_owner_id:string|null;control_points:number;resource_bonus:Record<string,unknown>;tax_rate:number;fishing_rights:boolean;mining_rights:boolean;creature_spawn_bonus:number;trade_bonus:number}
interface FortressRow{id:string;realm_id:string;territory_id:string;name:string;level:number;health:number;max_health:number;garrison_power:string;active:boolean}
interface RouteRow{id:string;owner_user_id:string|null;guild_id:string|null;realm_id:string|null;source_territory_id:string;destination_territory_id:string;resource_key:string;quantity:string;travel_seconds:number;status:string;next_departure:Date;last_completed_at:Date|null}
export const REALM_NAMES=["Sunken Kingdom","Storm Empire","Dragon Dominion","Mermaid Confederacy","Pirate Freeholds","Ancient Guardians"] as const;
function reputationTier(v:number){if(v>=5000)return"exalted";if(v>=2500)return"friendly";if(v>=500)return"respected";if(v<=-5000)return"hostile";if(v<=-2500)return"unfriendly";return"neutral"}
async function lockUser(c:PoolClient,userId:string){if(!(await c.query("SELECT id FROM users WHERE id=$1 FOR UPDATE",[userId])).rows[0])throw new Error("PLAYER_NOT_FOUND")}
export class RealmStore{
 constructor(private readonly db:Pool){}
 async list():Promise<RealmRow[]>{return (await this.db.query<RealmRow>("SELECT id,name,faction_type,population,economy,military_strength,resources,ai_state,capital_x,capital_y FROM realms ORDER BY name")).rows}
 async territories():Promise<TerritoryRow[]>{return (await this.db.query<TerritoryRow>("SELECT id,name,min_x,max_x,min_y,max_y,realm_owner_id,guild_owner_id,control_points,resource_bonus,tax_rate,fishing_rights,mining_rights,creature_spawn_bonus,trade_bonus FROM territories ORDER BY name")).rows}
 async territoryAt(x:number,y:number){if(!Number.isSafeInteger(x)||!Number.isSafeInteger(y))throw new Error("INVALID_TERRITORY_COORDINATES");return (await this.db.query<Pick<TerritoryRow,"id"|"name"|"realm_owner_id"|"guild_owner_id"|"control_points"|"resource_bonus"|"tax_rate"|"fishing_rights"|"mining_rights"|"creature_spawn_bonus"|"trade_bonus">>("SELECT id,name,realm_owner_id,guild_owner_id,control_points,resource_bonus,tax_rate,fishing_rights,mining_rights,creature_spawn_bonus,trade_bonus FROM territories WHERE min_x<=$1 AND max_x>=$1 AND min_y<=$2 AND max_y>=$2 ORDER BY (max_x-min_x)*(max_y-min_y),id LIMIT 1",[x,y])).rows[0]??null}
 private async guildInfluence(c:PoolClient,territoryId:string,guildId:string){const bases=await c.query<{id:string}>("SELECT b.id FROM player_bases b WHERE b.x BETWEEN (SELECT min_x FROM territories WHERE id=$1) AND (SELECT max_x FROM territories WHERE id=$1) AND b.y BETWEEN (SELECT min_y FROM territories WHERE id=$1) AND (SELECT max_y FROM territories WHERE id=$1) AND b.owner_user_id IN (SELECT user_id FROM guild_members WHERE guild_id=$2)",[territoryId,guildId]);if(!bases.rows.length)return 0n;const r=await c.query<{power:string}>("SELECT COALESCE(SUM(au.attack*au.quantity+au.defense*au.quantity),0)::text power FROM army_garrisons ag JOIN army_units au ON au.army_id=ag.army_id WHERE ag.base_id=ANY($1::uuid[])",[bases.rows.map(x=>x.id)]);return BigInt(r.rows[0]?.power??"0")}
 async claimGuildTerritory(userId:string,territoryId:string,guildId:string){const c=await this.db.connect();try{await c.query("BEGIN");await lockUser(c,userId);const m=await c.query<{rank:string}>("SELECT rank FROM guild_members WHERE guild_id=$1 AND user_id=$2 FOR UPDATE",[guildId,userId]);if(!m.rows[0]||!["master","officer"].includes(m.rows[0].rank))throw new Error("GUILD_PERMISSION_DENIED");if(!(await c.query("SELECT id FROM territories WHERE id=$1 FOR UPDATE",[territoryId])).rows[0])throw new Error("TERRITORY_NOT_FOUND");const influence=await this.guildInfluence(c,territoryId,guildId);if(influence<1000n)throw new Error("INSUFFICIENT_TERRITORY_INFLUENCE");await c.query("UPDATE territories SET guild_owner_id=$2,realm_owner_id=NULL,control_points=GREATEST(control_points,100),updated_at=CURRENT_TIMESTAMP WHERE id=$1",[territoryId,guildId]);await c.query("INSERT INTO territory_influence(territory_id,actor_type,actor_id,influence) VALUES($1,'guild',$2,$3) ON CONFLICT(territory_id,actor_type,actor_id) DO UPDATE SET influence=EXCLUDED.influence,updated_at=CURRENT_TIMESTAMP",[territoryId,guildId,influence.toString()]);await c.query("COMMIT");return this.territories()}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async reputation(userId:string,realm:string,delta:number){if(!Number.isSafeInteger(delta)||Math.abs(delta)>1000)throw new Error("INVALID_REPUTATION_DELTA");const c=await this.db.connect();try{await c.query("BEGIN");await lockUser(c,userId);const r=await c.query<{id:string}>("SELECT id FROM realms WHERE id::text=$1 OR name=$1",[realm]);if(!r.rows[0])throw new Error("REALM_NOT_FOUND");const old=await c.query<{reputation:number}>("SELECT reputation FROM realm_reputation WHERE realm_id=$1 AND user_id=$2 FOR UPDATE",[r.rows[0].id,userId]);const next=Math.max(-10000,Math.min(10000,(old.rows[0]?.reputation??0)+delta));await c.query("INSERT INTO realm_reputation(realm_id,user_id,reputation,tier) VALUES($1,$2,$3,$4) ON CONFLICT(realm_id,user_id) DO UPDATE SET reputation=EXCLUDED.reputation,tier=EXCLUDED.tier,updated_at=CURRENT_TIMESTAMP",[r.rows[0].id,userId,next,reputationTier(next)]);await c.query("COMMIT");return {realmId:r.rows[0].id,reputation:next,tier:reputationTier(next)}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async myReputation(userId:string):Promise<Array<{realm_id:string;name:string;reputation:number;tier:string}>>{return (await this.db.query<{realm_id:string;name:string;reputation:number;tier:string}>("SELECT r.id realm_id,r.name,COALESCE(rr.reputation,0) reputation,COALESCE(rr.tier,'neutral') tier FROM realms r LEFT JOIN realm_reputation rr ON rr.realm_id=r.id AND rr.user_id=$1 ORDER BY r.name",[userId])).rows}
 async createTradeRoute(userId:string,sourceId:string,destinationId:string,resourceKey:string,quantity:string,travelSeconds:number,guildId:string|null,realmId:string|null){if(!/^\d+$/.test(quantity)||BigInt(quantity)<=0n||!Number.isSafeInteger(travelSeconds)||travelSeconds<1||travelSeconds>604800)throw new Error("INVALID_TRADE_ROUTE");if(sourceId===destinationId)throw new Error("INVALID_TRADE_ROUTE_ENDPOINTS");const c=await this.db.connect();try{await c.query("BEGIN");await lockUser(c,userId);if(!(await c.query("SELECT id FROM territories WHERE id=$1",[sourceId])).rows[0]||!(await c.query("SELECT id FROM territories WHERE id=$1",[destinationId])).rows[0])throw new Error("INVALID_TRADE_ROUTE_ENDPOINTS");if(guildId&&!(await c.query("SELECT 1 FROM guild_members WHERE guild_id=$1 AND user_id=$2",[guildId,userId])).rows[0])throw new Error("GUILD_MEMBERSHIP_REQUIRED");const r=await c.query<{id:string}>("INSERT INTO trade_routes(owner_user_id,guild_id,realm_id,source_territory_id,destination_territory_id,resource_key,quantity,travel_seconds) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[userId,guildId,realmId,sourceId,destinationId,resourceKey.trim(),quantity,travelSeconds]);await c.query("COMMIT");return r.rows[0].id}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
 async fortresses():Promise<FortressRow[]>{return (await this.db.query<FortressRow>("SELECT id,realm_id,territory_id,name,level,health,max_health,garrison_power,active FROM realm_fortresses ORDER BY realm_id,name")).rows}
 async routes():Promise<RouteRow[]>{return (await this.db.query<RouteRow>("SELECT id,owner_user_id,guild_id,realm_id,source_territory_id,destination_territory_id,resource_key,quantity,travel_seconds,status,next_departure,last_completed_at FROM trade_routes ORDER BY next_departure,id")).rows}
 async tickAI(){const c=await this.db.connect();try{await c.query("BEGIN");const rs=await c.query<{id:string;population:string;economy:string;military_strength:string}>("SELECT id,population,economy,military_strength FROM realms FOR UPDATE");for(const r of rs.rows){const t=await c.query<{count:string}>("SELECT COUNT(*)::text count FROM territories WHERE realm_owner_id=$1",[r.id]);const count=BigInt(t.rows[0]?.count??"0"),economy=BigInt(r.economy)+count*25n,military=BigInt(r.military_strength)+count*10n;await c.query("UPDATE realm_fortresses SET garrison_power=GREATEST(garrison_power,$2),updated_at=CURRENT_TIMESTAMP WHERE realm_id=$1 AND active=true",[r.id,(military/10n).toString()]);await c.query("UPDATE realms SET economy=$2,military_strength=$3,ai_state=$4::jsonb,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[r.id,economy.toString(),military.toString(),JSON.stringify({mood:count>2n?"expanding":"stable",priority:military>economy?"military":"economy"})]);await c.query("INSERT INTO realm_ai_events(realm_id,event_type,payload) VALUES($1,'tick',$2::jsonb)",[r.id,JSON.stringify({territories:count.toString(),economy:economy.toString(),military:military.toString()})])}await c.query("UPDATE trade_routes SET last_completed_at=CURRENT_TIMESTAMP,next_departure=CURRENT_TIMESTAMP+(travel_seconds||' seconds')::interval WHERE status='active' AND next_departure<=CURRENT_TIMESTAMP");await c.query("COMMIT")}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
}