import type {Pool} from "pg";

export const SHIP_CLASSES={
  raft:{hull:100,armor:5,speed:2,turnRate:1.8,cargo:100,crew:2,cannons:1,sail:10,fuel:100,cost:{wood:100}},
  dinghy:{hull:140,armor:8,speed:2.5,turnRate:1.9,cargo:150,crew:3,cannons:1,sail:12,fuel:120,cost:{wood:150}},
  sloop:{hull:220,armor:12,speed:3.2,turnRate:2.0,cargo:250,crew:5,cannons:4,sail:16,fuel:180,cost:{wood:300,steel:50}},
  cutter:{hull:280,armor:16,speed:3.5,turnRate:2.2,cargo:300,crew:6,cannons:6,sail:18,fuel:220,cost:{wood:400,steel:100}},
  brig:{hull:420,armor:22,speed:3.1,turnRate:1.8,cargo:500,crew:10,cannons:10,sail:20,fuel:300,cost:{wood:700,steel:200}},
  frigate:{hull:600,armor:30,speed:3.4,turnRate:1.7,cargo:700,crew:16,cannons:18,sail:24,fuel:400,cost:{wood:1200,steel:400}},
  galleon:{hull:900,armor:40,speed:2.7,turnRate:1.3,cargo:1200,crew:25,cannons:24,sail:28,fuel:550,cost:{wood:2000,steel:700}},
  "dragon_ship":{hull:1200,armor:55,speed:4.0,turnRate:1.8,cargo:1000,crew:30,cannons:30,sail:35,fuel:700,cost:{wood:3000,steel:1200}},
  "ancient_warship":{hull:1800,armor:75,speed:3.6,turnRate:1.5,cargo:1600,crew:40,cannons:40,sail:40,fuel:900,cost:{wood:5000,steel:2500}},
} as const;
export type ShipClass=keyof typeof SHIP_CLASSES;
export const CREW_ROLES=["captain","navigator","gunner","engineer","medic","scout","boarding_specialist"] as const;
export type CrewRole=typeof CREW_ROLES[number];
export const CANNONBALL_ITEM="cannonball";
export interface Ship{id:string;ownerUserId:string;name:string;shipClass:ShipClass;hull:number;maxHull:number;armor:number;speed:number;turnRate:number;cargoCapacity:number;crewCapacity:number;cannonCount:number;sailPower:number;fuel:number;maxFuel:number;x:number;y:number;heading:number;status:"active"|"destroyed"|"docked";}
export interface ShipCrew{id:string;shipId:string;creatureId:string|null;npcType:string;role:CrewRole;skill:number;morale:number;}
export interface ShipInventoryItem{itemId:string;quantity:number;}
interface ShipRow{id:string;owner_user_id:string;name:string;ship_class:ShipClass;hull:number;max_hull:number;armor:number;speed:number;turn_rate:number;cargo_capacity:number;crew_capacity:number;cannon_count:number;sail_power:number;fuel:number;max_fuel:number;x:number;y:number;heading:number;status:Ship["status"];}
function toShip(r:ShipRow):Ship{return{id:r.id,ownerUserId:r.owner_user_id,name:r.name,shipClass:r.ship_class,hull:r.hull,maxHull:r.max_hull,armor:r.armor,speed:r.speed,turnRate:r.turn_rate,cargoCapacity:r.cargo_capacity,crewCapacity:r.crew_capacity,cannonCount:r.cannon_count,sailPower:r.sail_power,fuel:r.fuel,maxFuel:r.max_fuel,x:r.x,y:r.y,heading:r.heading,status:r.status};}
function shipRowSelect(){return"id,owner_user_id,name,ship_class,hull,max_hull,armor,speed,turn_rate,cargo_capacity,crew_capacity,cannon_count,sail_power,fuel,max_fuel,x,y,heading,status";}
function safeInteger(n:unknown):n is number{return typeof n==="number"&&Number.isSafeInteger(n);}
export class ShipStore{
 private readonly operations=new Map<string,Promise<void>>(); constructor(private readonly db:Pool){}
 private async exclusive<T>(userId:string,op:()=>Promise<T>):Promise<T>{const previous=this.operations.get(userId)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(r=>{release=r});const queued=previous.catch(()=>undefined).then(()=>gate);this.operations.set(userId,queued);await previous.catch(()=>undefined);try{return await op()}finally{release();if(this.operations.get(userId)===queued)this.operations.delete(userId);}}
 async create(userId:string,name:string,shipClass:ShipClass):Promise<Ship>{return this.exclusive(userId,async()=>{const spec=SHIP_CLASSES[shipClass];if(!spec)throw new Error("INVALID_SHIP_CLASS");const client=await this.db.connect();try{await client.query("BEGIN");const base=await client.query<{id:string}>("SELECT id FROM player_bases WHERE owner_user_id=$1 FOR UPDATE",[userId]);if(!base.rows[0])throw new Error("BASE_NOT_FOUND");const yard=await client.query<{id:string}>("SELECT id FROM base_buildings WHERE base_id=$1 AND type='shipyard' AND active=true LIMIT 1",[base.rows[0].id]);if(!yard.rows[0])throw new Error("SHIPYARD_REQUIRED");for(const [resource,quantity] of Object.entries(spec.cost)){const row=await client.query<{quantity:string}>("SELECT quantity FROM base_storage WHERE base_id=$1 AND resource_key=$2 FOR UPDATE",[base.rows[0].id,resource]);if(Number(row.rows[0]?.quantity??0)<quantity)throw new Error("INSUFFICIENT_SHIPYARD_RESOURCES");await client.query("UPDATE base_storage SET quantity=quantity-$3,updated_at=CURRENT_TIMESTAMP WHERE base_id=$1 AND resource_key=$2",[base.rows[0].id,resource,quantity]);}const inserted=await client.query<ShipRow>(`INSERT INTO player_ships(owner_user_id,name,ship_class,hull,max_hull,armor,speed,turn_rate,cargo_capacity,crew_capacity,cannon_count,sail_power,fuel,max_fuel) VALUES($1,$2,$3,$4,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) RETURNING ${shipRowSelect()}`,[userId,name.trim().slice(0,64)||shipClass,shipClass,spec.hull,spec.armor,spec.speed,spec.turnRate,spec.cargo,spec.crew,spec.cannons,spec.sail,spec.fuel]);await client.query("INSERT INTO ship_inventory(ship_id,item_id,quantity) VALUES($1,$2,$3)",[inserted.rows[0].id,CANNONBALL_ITEM,spec.cannons*2]);await client.query("COMMIT");return toShip(inserted.rows[0]);}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}})}
 async list(userId:string):Promise<Ship[]>{const r=await this.db.query<ShipRow>(`SELECT ${shipRowSelect()} FROM player_ships WHERE owner_user_id=$1 ORDER BY created_at,id`,[userId]);return r.rows.map(toShip);}
 async inventory(userId:string,shipId:string):Promise<ShipInventoryItem[]>{const r=await this.db.query<{item_id:string;quantity:string}>("SELECT i.item_id,i.quantity FROM ship_inventory i JOIN player_ships s ON s.id=i.ship_id WHERE i.ship_id=$1 AND s.owner_user_id=$2 ORDER BY i.item_id",[shipId,userId]);return r.rows.map(x=>({itemId:x.item_id,quantity:Number(x.quantity)}));}
 async sail(userId:string,shipId:string,dx:number,dy:number,dt:number):Promise<Ship>{return this.exclusive(userId,async()=>{if(!Number.isFinite(dx)||!Number.isFinite(dy)||!Number.isFinite(dt)||dt<=0||dt>60||Math.abs(dx)>1||Math.abs(dy)>1||(dx===0&&dy===0))throw new Error("INVALID_SAIL_INPUT");const client=await this.db.connect();try{await client.query("BEGIN");const r=await client.query<ShipRow>(`SELECT ${shipRowSelect()} FROM player_ships WHERE id=$1 AND owner_user_id=$2 FOR UPDATE`,[shipId,userId]);const ship=r.rows[0];if(!ship)throw new Error("SHIP_NOT_FOUND");if(ship.status!=="active")throw new Error("SHIP_NOT_ACTIVE");const distance=ship.speed*dt;const fuelCost=Math.max(1,Math.ceil(distance/ship.sail_power));if(ship.fuel<fuelCost)throw new Error("INSUFFICIENT_SHIP_FUEL");const heading=Math.atan2(dy,dx);const x=ship.x+dx*distance;const y=ship.y+dy*distance;const updated=await client.query<ShipRow>(`UPDATE player_ships SET x=$3,y=$4,heading=$5,fuel=fuel-$6,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND owner_user_id=$2 RETURNING ${shipRowSelect()}`,[shipId,userId,x,y,heading,fuelCost]);await client.query("COMMIT");return toShip(updated.rows[0]);}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}})}
 async assignCrew(userId:string,shipId:string,creatureId:string,role:CrewRole,skill=1,morale=100):Promise<ShipCrew>{return this.exclusive(userId,async()=>{if(!CREW_ROLES.includes(role)||!safeInteger(skill)||skill<1||skill>100||!safeInteger(morale)||morale<0||morale>100)throw new Error("INVALID_CREW_ASSIGNMENT");const client=await this.db.connect();try{await client.query("BEGIN");const ship=await client.query<{crew_capacity:number}>("SELECT crew_capacity FROM player_ships WHERE id=$1 AND owner_user_id=$2 FOR UPDATE",[shipId,userId]);if(!ship.rows[0])throw new Error("SHIP_NOT_FOUND");const count=await client.query<{count:string}>("SELECT COUNT(*)::text count FROM ship_crew WHERE ship_id=$1",[shipId]);if(Number(count.rows[0]?.count??0)>=ship.rows[0].crew_capacity)throw new Error("SHIP_CREW_CAPACITY_REACHED");const creature=await client.query<{owner_user_id:string;tame_progress:number;party_slot:number|null}>("SELECT owner_user_id,tame_progress,party_slot FROM player_creatures WHERE id=$1 FOR UPDATE",[creatureId]);if(!creature.rows[0]||creature.rows[0].owner_user_id!==userId)throw new Error("CREW_CREATURE_NOT_FOUND");if(creature.rows[0].tame_progress<100)throw new Error("CREW_CREATURE_NOT_TAMED");if(creature.rows[0].party_slot!==null)throw new Error("CREW_CREATURE_IN_PARTY");const existing=await client.query<{id:string}>("SELECT id FROM ship_crew WHERE creature_id=$1",[creatureId]);if(existing.rows[0])throw new Error("CREW_ALREADY_ASSIGNED");const inserted=await client.query<{id:string}>("INSERT INTO ship_crew(ship_id,creature_id,owner_user_id,npc_type,role,skill,morale) VALUES($1,$2,$3,'creature',$4,$5,$6) RETURNING id",[shipId,creatureId,userId,role,skill,morale]);await client.query("COMMIT");return{id:inserted.rows[0].id,shipId,creatureId,npcType:"creature",role,skill,morale};}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}})}
 async fireCannon(userId:string,shipId:string,targetShipId:string):Promise<{attacker:Ship;target:Ship;damage:number}>{return this.exclusive(userId,async()=>{const client=await this.db.connect();try{await client.query("BEGIN");const shipsR=await client.query<ShipRow>(`SELECT ${shipRowSelect()} FROM player_ships WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE`,[[shipId,targetShipId]]);const attacker=shipsR.rows.find(s=>s.id===shipId);const target=shipsR.rows.find(s=>s.id===targetShipId);if(!attacker)throw new Error("SHIP_NOT_FOUND");if(!target||target.owner_user_id===userId)throw new Error("INVALID_NAVAL_TARGET");if(attacker.status!=="active")throw new Error("SHIP_NOT_ACTIVE");if(target.status!=="active")throw new Error("TARGET_SHIP_NOT_ACTIVE");if(Math.hypot(attacker.x-target.x,attacker.y-target.y)>250)throw new Error("NAVAL_TARGET_OUT_OF_RANGE");const recent=await client.query<{created_at:Date}>("SELECT created_at FROM naval_combat_events WHERE attacker_ship_id=$1 ORDER BY created_at DESC LIMIT 1",[shipId]);if(recent.rows[0]&&Date.now()-new Date(recent.rows[0].created_at).getTime()<1000)throw new Error("CANNON_COOLDOWN");const ammo=await client.query<{quantity:string}>("SELECT quantity FROM ship_inventory WHERE ship_id=$1 AND item_id=$2 FOR UPDATE",[shipId,CANNONBALL_ITEM]);if(Number(ammo.rows[0]?.quantity??0)<1)throw new Error("NO_CANNON_AMMO");const crew=await client.query<{skill:number}>("SELECT skill FROM ship_crew WHERE ship_id=$1 AND role='gunner'",[shipId]);const gunnerBonus=crew.rows.reduce((sum,c)=>sum+c.skill,0);const damage=Math.max(1,attacker.cannon_count+Math.floor(gunnerBonus/10)-target.armor);const hull=Math.max(0,target.hull-damage);const status=hull===0?"destroyed":target.status;await client.query("UPDATE ship_inventory SET quantity=quantity-1,updated_at=CURRENT_TIMESTAMP WHERE ship_id=$1 AND item_id=$2",[shipId,CANNONBALL_ITEM]);const updated=await client.query<ShipRow>(`UPDATE player_ships SET hull=$2,status=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING ${shipRowSelect()}`,[target.id,hull,status]);await client.query("INSERT INTO naval_combat_events(attacker_ship_id,defender_ship_id,attacker_user_id,defender_user_id,damage,attacker_hull_after,defender_hull_after) VALUES($1,$2,$3,$4,$5,$6,$7)",[attacker.id,target.id,userId,target.owner_user_id,damage,attacker.hull,hull]);await client.query("COMMIT");return{attacker:toShip(attacker),target:toShip(updated.rows[0]),damage};}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}})}
}
